### ISSUE TITLE
Switch to Jekyll

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis.io#112]
After much research and discussion, we'll be moving from Hugo to Jekyll for the community site. This will allow us to handle ascii-doctor better, making porting over and maintaining the Developer Handbook easier for contributors, and we'll also have access to a much more active and developed community.

**Comment by kahboom** [comment]
cc @zregvart - Continuing the discussion about whether or not to host the docs on the syndesis.io repo or keeping them in the syndesis code base, I just wanted to point out that this issue was created with the intention of migrating the dev docs + handbook to the website repo.

I think this decision may need to be revisited to ensure that the people that currently contribute to it will actually continue to do so, or if they need it to stay where it is? If that's the case, we can still build the docs with CD/CI to make them available on the website in a way that looks like it's "native" to the site, or integrated.

**Comment by zregvart** [comment]
I think the developers handbook, currently situated in [doc/sdh](https://github.com/syndesisio/syndesis/tree/70de248b8d91317619b0d86131c9fedf47892df2/doc/sdh) of the syndesis git repository should be moved over to the website. 

I think this would enable quicker turnaround on the editing and publishing of the developer documentation.

For the user documentation, most of the other directories/files in [doc](https://github.com/syndesisio/syndesis/tree/70de248b8d91317619b0d86131c9fedf47892df2/doc) directory, that is other than `sdh` and `system-tests`, I think, it's better to have it versioned with the code. This will require additional work on the build of the website, or we could repurpose the existing domain `doc.syndesis.io` to host only the user documentation and publish it from a separate process, perhaps on stable release.
