### ISSUE TITLE
Cross-Browser Compatibility

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis.io#39]
Make sure that the website works well across multiple browsers. Will we need additional polyfills for things like the `affix` plugin, or special fallbacks?

@jimmidyson - Can you chime in here about which browsers we should be supporting?
- Chrome
- Firefox
- Safari
- IE 8+
- Opera

Perhaps worth taking a look at [caniuse.com](http://www.caniuse.com/) to see if what we are already using is compatible with certain browsers. :joy:

**Comment by dsimansk** [comment]
Hi, @kahboom! I wonder if you feel like we should fully automate this? :) Would it be sufficient to create screenshot in those browser per page to visually go through?

**Comment by jimmidyson** [comment]
We should be able to automate this but i'd prefer to use a oss (or at least free for oss) service if one exists.

**Comment by jimmidyson** [comment]
I'm happy to follow the bootstrap v4 compatibility btw - http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#supported-browsers - seems OK to me.

**Comment by kahboom** [comment]
@dsimansk - The screenshot approach, to me, makes the most sense for a static, not-super-interactive website. It'd definitely be cool to automate it.

@jimmidyson - Sounds good! 👍
