### ISSUE TITLE
Mobile: not all integration routes are displayed

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis.io#49]
Android 7.1.1, Chrome 58.0.x

Linkedin to Github is missing in mobile layout.

![screenshot_20170522-110645](https://cloud.githubusercontent.com/assets/5637792/26300671/144d031c-3edf-11e7-83c2-91473eabe23a.png)

**Comment by jimmidyson** [comment]
That was a conscious decision to keep large icons but have less info... open to changing if you @dsimansk or @kahboom can think of another option?

**Comment by dsimansk** [comment]
That makes sense for the mobile layout, looks all right to me as a concept of balancing images and text. I have no objections then. We can probably close the issue, if @kahboom feels the same way.

P.S.: Styling issue from #50 still applies. :)

**Comment by jimmidyson** [comment]
Closing...
