### ISSUE TITLE
Integration icons arrow color and spacing

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis.io#50]
First arrow color is not matching the rest of bunch. And notice the spacing on the last one also.

![screen shot 2017-05-22 at 11 14 46](https://cloud.githubusercontent.com/assets/5637792/26300998/11903d3c-3ee0-11e7-9b54-4e0838af2ba7.png)

**Comment by jimmidyson** [comment]
You've got such a good eye for detail... thanks!

**Comment by dsimansk** [comment]
Those smaller mobile screen make a difference for me to spot details :)

After looking at HTML, there's difference in closing `</a>` element placement between first row and the other two. Not sure what color/colour do we prefer for arrows though :)

**Comment by jimmidyson** [comment]
@dsimansk yeah I'm fixing up now thanks!

**Comment by jimmidyson** [comment]
Assigning after it's closed? Crazy talk!

**Comment by kahboom** [comment]
Wouldn't have it any other way than crazy. :grimacing:
