### ISSUE TITLE
Error deploying "syndesis" template from Getting Started Guide

### ISSUE THREAD

**Issue by aileenc** [syndesisio/syndesis.io#54]
When I follow the instructions in the Getting Started Guide 
- start minishift
- register github app
- install the template syndesis.yml
- deploy syndesis

I get the following error at deployment step:

error: User "developer" cannot create oauthclients at the cluster scope

**Comment by zregvart** [comment]
I think this might be related to #52

**Comment by jimmidyson** [comment]
Closing as this shouldn't be a problem any more - please reopen if I'm mistaken.
