### ISSUE TITLE
Table layout in markdown documents

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis.io#63]
The layout of Markdown tables is ugly:

* No borders
* No padding for the cells
* No margin at the bottom

You can see this in the https://syndesis.io/community/engineering_guidelines/

**Comment by jimmidyson** [comment]
Isn't that more CSS than a problem with markdown? @kahboom?

**Comment by kahboom** [comment]
Yes.. assigning to myself for post-demo

**Comment by kahboom** [comment]
This is fixed in my PR (I think, was so long ago), so need to update that this Friday.. as it can't be merged in yet due to a center content on the landing page causing side-scroll *cringe*..

**Comment by rhuss** [comment]
Yes, it's about CSS. Or the lack of, for tables in general.

**Comment by kahboom** [comment]
Fixed via https://github.com/syndesisio/syndesis.io/pull/107
